version: "3.7"

services:
  openwb:
    image: thelongandonly/openwb:latest
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    container_name: openwb
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Berlin"
      WEB_PORT: 9047
    tmpfs:
      - /var/www/html/openWB/ramdisk
    volumes:
      - /volume1/docker/openWB/config:/var/www/html/openWB/config
      - /volume1/docker/openWB/logdata:/var/www/html/openWB/web/logging/data

